ALTER TABLE `#__cleantalk_sfw` ADD source tinyint(1) NOT NULL DEFAULT 0 AFTER `status`;
DROP TABLE IF EXISTS `#__cleantalk_sfw_logs`;
CREATE TABLE IF NOT EXISTS `#__cleantalk_sfw_logs` (
    `id` VARCHAR(40) NOT NULL,
    `ip` VARCHAR(15) NOT NULL,
    `status` ENUM('PASS_SFW','DENY_SFW','PASS_SFW__BY_WHITELIST','PASS_SFW__BY_COOKIE','DENY_ANTICRAWLER','PASS_ANTICRAWLER','DENY_ANTICRAWLER_UA','PASS_ANTICRAWLER_UA','DENY_ANTIFLOOD','PASS_ANTIFLOOD') NULL DEFAULT NULL,
    `all_entries` INT NOT NULL,
    `blocked_entries` INT NOT NULL,
    `entries_timestamp` INT NOT NULL,
    `ua_id` INT(11) NULL DEFAULT NULL,
    `ua_name` VARCHAR(1024) NOT NULL,
    `source` TINYINT NULL DEFAULT NULL,
    `network` VARCHAR(20) NULL DEFAULT NULL,
    `first_url`VARCHAR(100) NULL DEFAULT NULL,
    `last_url` VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);